import { useGLTF } from "@react-three/drei";

export function Well(props) {
  const { nodes, materials } = useGLTF("/camp_world/Well.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20309.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20310.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20311.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20312.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20313.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20314.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20315.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20316.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20317.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20318.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20319.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20320.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20321.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20322.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20323.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20324.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20325.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20326.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20327.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20328.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20329.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20330.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20331.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20332.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20333.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20334.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20335.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20336.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20337.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20338.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20339.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20340.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20341.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20342.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20343.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20344.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20345.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20346.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20347.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20348.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20349.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20350.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20351.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20352.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20353.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20354.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20355.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20356.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20357.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20358.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20359.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20360.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20361.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20362.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20363.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20364.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20365.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20366.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20367.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20368.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20369.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20370.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20371.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20372.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20373.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20374.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20375.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20376.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20377.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20378.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20379.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20380.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20381.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20382.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20383.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20384.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20385.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20386.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20387.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20388.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20389.geometry}
        material={materials["02___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20390.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20391.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20392.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20393.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20394.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20395.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20396.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20397.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20398.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20399.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20400.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20401.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20402.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20403.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20404.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20405.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20406.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20407.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20408.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20409.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20410.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20411.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20412.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20413.geometry}
        material={materials["02___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20414.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20415.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20416.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20417.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20418.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20419.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20420.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20421.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20422.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20423.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20424.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20425.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20426.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20427.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20428.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20429.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20430.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20431.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20432.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20433.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20434.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box20435.geometry}
        material={materials._crayfishdiffuse}
      />
    </group>
  );
}

useGLTF.preload("/Well.glb");
