/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DeadTree(props) {
  const { nodes, materials } = useGLTF('inferno_world/Dead Tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DeadTree_2.geometry}
        material={materials.Bark_DeadTree}
      />
    </group>
  )
}

useGLTF.preload('/Dead Tree.glb')
export default DeadTree;