/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NeonSigns(props) {
  const { nodes, materials } = useGLTF('inferno_world/Cyberpunk Signs.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_3_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_3_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[0.72, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_2_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_2_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[1.44, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_1_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Small_1_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[2.459, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Small2_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Small2_2.geometry}
          material={materials.DarkGrey}
        />
      </group>
      <group position={[3.268, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Small1_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Small1_2.geometry}
          material={materials.DarkGrey}
        />
      </group>
      <group position={[4.509, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Hazard_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_Hazard_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[0.682, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_3_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_3_2.geometry}
          material={materials.DarkGrey}
        />
      </group>
      <group position={[2.015, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_2_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_2_2.geometry}
          material={materials.DarkGrey}
        />
      </group>
      <group position={[3.347, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_1_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_Corner_1_2.geometry}
          material={materials.DarkGrey}
        />
      </group>
      <group position={[-0.234, 2.5, -0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_4_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_4_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[0.899, 2.5, -0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_3_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_3_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[2.422, 2.5, -0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_2_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_2_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[3.956, 2.5, -0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_1_1.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sign_1_2.geometry}
          material={materials.Grey}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Cyberpunk Signs.glb')

export default NeonSigns;