/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Speakers(props) {
  const { nodes, materials } = useGLTF('inferno_world/Wall desk speakers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallDeskSpeakers_mesh.geometry}
        material={materials.lambert3SG}
      />
    </group>
  )
}

useGLTF.preload('/Wall desk speakers.glb')
export default Speakers;